name: Flujo_trabajo # Nombre del flujo de trabajo

# Evento que activa el flujo de trabajo
on:
  push:
    branches:
      - main
# El flujo se ejecutará cada vez que haya un push a la rama main.

jobs:
  example-job:
    runs-on: ubuntu-latest # Se ejecuta en la última versión de Ubuntu
    
    steps:
      # Paso 1: Checkout del código
      - name: Checkout code
        uses: actions/checkout@v3
        # Clona el código fuente para que el runner pueda usarlo.

      # Paso 2: Uso del GITHUB_TOKEN
      - name: Use GITHUB_TOKEN
        run: |
          curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/user/repos